filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/vendor/angular/*'
    - 'js/vendor/angular-enhance-text.min.js'
    - 'js/vendor/jquery.autosize.min.js'
    - 'js/vendor/rangyinputs.js.js'

imports:
    - javascript
    - php

tools:
    external_code_coverage: true
    js_hint:
    use_native_config: true

    php_mess_detector:
        config:
            controversial_rules:
                camel_case_class_name: true
                camel_case_property_name: true
                camel_case_method_name: true
                camel_case_parameter_name: true
                camel_case_variable_name: true
                superglobals: false

    php_code_sniffer:
        config:
            sniffs:
                generic:
                    white_space:
                        disallow_space_indent_sniff: true
