filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/vendor/*' # Minified from /js/src/bower_components
    - 'js/main.min.js' # Minified from /js/src/*
    - 'js/src/bower_components/*' # thirdparty
imports:
 - javascript
 - php

tools:
    external_code_coverage:
        timeout: 600