filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/vendor/angular/*'
    - 'js/vendor/angular-enhance-text.js'
    - 'js/vendor/jquery.autosize.js'
    - 'js/vendor/rangyinputs.js.js'

imports:
 - javascript
 - php

tools:
    external_code_coverage:
        timeout: 600