filter:
  excluded_paths:
    - 'l10n/*'
    - 'js/main.min.js' # Minified from /js/src/*
    - 'vendor/*' # thirdparty

imports:
 - javascript
 - php

tools:
    external_code_coverage:
      timeout: 600
checks:
    php:
        duplication: false