language: php

matrix:
  include:
    - php: 5.3
      env: DB=sqlite
    - php: 5.4
      env: DB=sqlite
    - php: 5.5
      env: DB=sqlite
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=mysql

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh chat master $DB

script:
  - cd ../core/apps/chat
  - make test
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover