language: php

matrix:
  include:
    - php: 5.4
      env: DB=sqlite
    - php: 5.5
      env: DB=sqlite
    - php: 5.6
      env: DB=sqlite
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=mysql

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get -y install nodejs
  - npm install
  # install ocdev
  - sudo apt-get -y install python3-jinja2 python3-setuptools
  - sudo easy_install3 requests
  - sudo easy_install3 ocdev
  # set up postgresql
  - createuser -U travis -s oc_autotest
  # set up mysql
  - mysql -e 'create database oc_autotest;'
  - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost';"
  - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
  # install owncloud
  - cd ..
  - ocdev setup core --dir owncloud --branch $BRANCH --no-history
  - mv chat owncloud/apps/chat
  - phpenv config-add owncloud/apps/chat/tests/travis/php.ini
  - cd owncloud
  - ocdev ci $DB
  - php -f console.php app:enable CHAT

before_script:
  - cd apps/chat
  - composer install

script:
  - grunt tests
