language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
- DB=sqlite

before_install:
  - sh tests/install_dependencies.sh
  - sh tests/setup_owncloud.sh

script:
  - phpunit -c tests/phpunit.xml --testsuite app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover