language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh chat master $DB

script:
  - cd ../core/apps/chat
  - phpunit -c tests/phpunit.xml --testsuite database
